[build]
  # Pas de commande de build car c'est un site statique
  command = "echo 'Site statique - déploiement direct'"
  # Dossier à publier (racine du projet)
  publish = "."

# Redirections pour les pages HTML
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Gestion des erreurs 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
